Add home page
techmmunity/unique-login-sytem-front pull request #2
Opened 2021-05-13 11:52 UTC by alessandrohenriqueramos

2021-05-13 12:11 UTC, henriqueleite42 requested changes

2021-05-13 12:11 UTC, henriqueleite42 commented on src/assets/colors.ts
> +	gray50: "#d9e3e4",
Remover todas essas cores e extender elas da config do repo core

2021-05-13 12:11 UTC, henriqueleite42 commented on src/assets/images/svg/behance.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Behance icon</title><path d="M0 4.4804V19.243h7.1554c.6613 0 1.3078-.0832 1.9297-.248.6288-.1654 1.1905-.4203 1.6792-.766
Formatar esse arquivo

2021-05-13 12:11 UTC, henriqueleite42 commented on src/assets/images/svg/dribbble.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Dribbble icon</title><path d="M12 24C5.385 24 0 18.615 0 12S5.385 0 12 0s12 5.385 12 12-5.385 12-12 12zm10.12-10.358c-.35
Formatar esse arquivo

2021-05-13 12:11 UTC, henriqueleite42 commented on src/assets/images/svg/stackoverflow.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Stack Overflow icon</title><path d="M15.725 0l-1.72 1.277 6.39 8.588 1.716-1.277L15.725 0zm-3.94 3.418l-1.369 1.644 8.225
Formatar esse arquivo

2021-05-13 12:11 UTC, henriqueleite42 commented on src/assets/translations/en-US/common.json
> +				"email": "Login with email",
`Log in`

2021-05-13 12:11 UTC, henriqueleite42 commented on src/assets/translations/pt-BR/common.json
> +					"title": "Eu sou um desenvolvedor!"
`Desenvolvedor`

2021-05-13 12:11 UTC, henriqueleite42 commented on src/assets/translations/pt-BR/common.json
> +					"title": "Eu sou um gerente!"
`Gerente`

2021-05-13 12:11 UTC, henriqueleite42 commented on src/web/pages/Home/components/MainSection/components/LinkWithIcon/styles.ts
> +	${Container} > a:hover
Aqui, se colocasse só `${Container} > a:hover, a:focus, a:active` ou
```
${Container} > a {
   &:focus,
   &:active,
  &:hover {
  }
}
```
Não funcionaria?

2021-05-13 12:11 UTC, henriqueleite42 commented on src/web/pages/Home/components/MainSection/index.tsx
> +				<Links>
Transformar isso em um componente, que receba um titulo e os botões

2021-05-13 12:11 UTC, henriqueleite42 commented on src/web/pages/Home/components/MainSection/index.tsx
> +						{mainLinks.linksWithoutIcon.map(({ id, ...props }) => (
Deixar isso estático

2021-05-13 16:33 UTC, henriqueleite42 requested changes

2021-05-13 16:33 UTC, henriqueleite42 commented on src/web/pages/Home/components/MainSection/components/Links/index.tsx
> +		{children}
Separar isso em outro componente

2021-05-14 12:30 UTC, henriqueleite42 requested changes

2021-05-14 12:30 UTC, henriqueleite42 commented on src/assets/translations/pt-BR/common.json
> +					"title": "Eu sou um Gerente!"
`Gerente` > `Gestor`

2021-05-14 12:30 UTC, henriqueleite42 commented on src/web/pages/Home/index.tsx
> +export const Home: FCWithLayout = () => (
`Home` > `HomePage`

2021-05-14 12:30 UTC, henriqueleite42 commented on src/web/pages/Home/index.tsx
> +			<MainSection />
A `MainSection` deve ser separada em 2 componentes, a `HomeImage` e a `LinksBar` (ou algum nome melhor).

2021-05-14 12:39 UTC, henriqueleite42 requested changes

2021-05-14 12:39 UTC, henriqueleite42 commented on src/web/pages/Home/components/MainSection/index.tsx
> +				<LinksWithoutIcon>
Aumentar um pouco o espaçamento entre "Log in with email" e "I forgot my password", e diminuir um pouco o tamanho da fonte.

2021-05-14 15:41 UTC, alessandrohenriqueramos commented on src/web/pages/Home/index.tsx
> +			<MainSection />
Corrigido

2021-05-14 16:46 UTC, henriqueleite42 requested changes

2021-05-14 16:46 UTC, henriqueleite42 commented on src/assets/translations/pt-BR/common.json
> +					"title": "Eu sou Designer Gráfico!"
`Eu sou um`

2021-05-14 16:50 UTC, henriqueleite42 approved these changes

2021-05-14 16:50 UTC, merged