Add apps page
techmmunity/unique-login-sytem-front pull request #6
Opened 2021-05-19 12:32 UTC by alessandrohenriqueramos

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] I followed GitFlow pattern to create the branch
- [x] My code produces no warnings or errors in the console
- [x] Tests for the changes have been added / updated
- [x] Docs have been added / updated

## PR Type

What kind of change does this PR introduce?
It adds a techmmunity app page

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
No apps page

## What is the new behavior?

## Does this PR introduce a breaking change?
Added apps page

```
[ ] Yes
[x] No
```

## Other information (Prints, details, etc)
![image](https://user-images.githubusercontent.com/70819804/118812958-0f319180-b885-11eb-893a-5abede95b1cc.png)

2021-05-19 13:28 UTC, henriqueleite42 requested changes

2021-05-19 13:28 UTC, henriqueleite42 commented on src/assets/translations/en-US/common.json
> +			"title": "Apps | Techmmunity"
Abistrair esse ` | Techmmunity` em um arquivo de config

2021-05-19 13:28 UTC, henriqueleite42 commented on src/assets/translations/pt-BR/common.json
> +			"title": "Aplicativos | Techmmunity"
Abistrair esse ` | Techmmunity` em um arquivo de config

2021-05-19 13:28 UTC, henriqueleite42 commented on src/web/pages/App/styles.ts
> +		&:focus {
A outline não pode ser removida, remover esse `&:focus`

Obs: Sempre que "focus" for usado, tbm é necessário usar &:active

2021-05-19 13:28 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/components/SearchBar/index.tsx
> +	const [data, setData] = useState("");
Remover esse state, ele será adicionado em outro PR

2021-05-19 13:28 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/components/SearchBar/index.tsx
> +	const handleSubmit = useCallback((e: FormEvent) => e.preventDefault(), []);
Alterar o nome para "preventSubmit"

2021-05-19 13:28 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/index.tsx
> +				<Title>Techmmunity</Title>
`Techmmunity Apps` e `Aplicativos Techmmunity`

2021-05-19 13:28 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/styles.ts
> +	&:disabled {
Alterar isso paraser uma custom prop `active`, que faz o inverso do que está fazendo hoje.

2021-05-30 12:29 UTC, alessandrohenriqueramos commented on src/web/pages/App/styles.ts
> +		&:focus {
errado sobre o active, ele só funciona em links

2021-05-30 15:36 UTC, henriqueleite42 requested changes

2021-05-30 15:36 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/components/App/index.tsx
> +	return (
Adicionar espaço

2021-05-30 15:36 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/components/App/index.tsx
> +				<Link href={`${query.apps}${url}`}>
"href={`${query.apps}${url}`}" -> `href={url}`
O usuário será redirecionado para fora da ULS, então adicionar um prefixo a rota é um comportamento incorreto.

2021-05-30 15:36 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/index.tsx
> +				"Discord is the easiest way to talk over voice, video, and text. Talk, chat, hang out, and stay close with your friends and communities.",
A descrição e o titulo serão traduzidos, adicionar esses dados no json da i18n

2021-05-30 23:08 UTC, alessandrohenriqueramos commented on src/web/pages/Apps/components/AppsSection/components/App/index.tsx
> +	return (
Removido essa parte

2021-05-30 23:27 UTC, henriqueleite42 requested changes

2021-05-30 23:27 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/components/App/index.tsx
> +	return (
Remover `return` e retornar diretamente `(`

2021-05-30 23:27 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/styles.ts
> +const ButtonCSS = css`
Alterar o nome para `BaseButton`, transformar isso em um `styled.button<{active?:boolean}>`, e usar `styled(BaseButton)` nos lugares para extender os estilos

2021-05-30 23:34 UTC, henriqueleite42 requested changes

2021-05-30 23:34 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/styles.ts
> +	padding: 1rem 0;
Adicionar uma margin (ou padding) de `5 rem` acima e abaixo desse componente.

2021-05-30 23:34 UTC, henriqueleite42 commented on src/web/pages/Apps/components/AppsSection/components/App/styles.ts
> +export const Desktop = styled.li`
Fazer com que quando a pessoa passe o mouse por cima, o componente todo fique com uma aparecencia mais clara (acho que dá pra fazer isso usando `filter` do css.)

2021-05-31 22:57 UTC, alessandrohenriqueramos commented on src/web/pages/Apps/components/AppsSection/components/App/styles.ts
> +export const Desktop = styled.li`
adicionar scale

2021-06-01 15:38 UTC, henriqueleite42 approved these changes

2021-06-01 15:39 UTC, merged